osm:
  global:
    hostname: "tailac05db.ts.net"
    ingressClassName: tailscale
    tailscaleProxyClass: default-proxy-class
    gitops:
      enabled: true
      gitUser: osm-developer
      gitBaseUrl: http://gitea-http.gitea.svc.cluster.local:3000
      fleetRepoUrl: http://gitea-http.gitea.svc.cluster.local:3000/osm-developer/fleet-osm
      swcatalogsRepoUrl: http://gitea-http.gitea.svc.cluster.local:3000/osm-developer/sw-catalogs-osm
      mgmtcluster:
        secretName: mgmtcluster-secret
        secretKey: kubeconfig
      auxcluster:
        secretName: auxcluster-secret
        secretKey: kubeconfig
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule

  mongodb:
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule
    arbiter:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    persistence:
      storageClass: "pd-standard"
      size: 8Gi

  kafka:
    controller:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
      persistence:
        storageClass: "pd-standard"
        size: 8Gi
    zookeeper:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule

  mysql:
    primary:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule

  prometheus:
    kube-state-metrics:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    server:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
      persistentVolume:
        storageClass: "pd-standard"
        size: 8Gi
      ingress:
        ingressClassName: tailscale
        annotations:
          tailscale.com/proxy-class: default-proxy-class
        hosts:
          - "setup02-prometheus.tailac05db.ts.net"
        tls:
          - secretName: prometheus-cert
            hosts:
              - "setup02-prometheus.tailac05db.ts.net"
    alertmanager:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    prometheus-pushgateway:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule

  grafana:
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule
    persistence:
      enabled: true
      storageClassName: "pd-standard"
      size: 2Gi
    ingress:
      ingressClassName: tailscale
      annotations:
        tailscale.com/proxy-class: default-proxy-class
      hosts:
        - "setup02-grafana.tailac05db.ts.net"
      tls:
        - secretName: grafana-cert
          hosts:
            - "setup02-grafana.tailac05db.ts.net"

  nbi:
    ingress:
      host: "setup02-nbi.tailac05db.ts.net"

  ngui:
    ingress:
      host: "setup02-gui.tailac05db.ts.net"

  alertmanager:
    ingress:
      host: "setup02-alertmanager.tailac05db.ts.net"

  webhookTranslator:
    ingress:
      host: "setup02-webhook.tailac05db.ts.net"

  airflow:
    ingress:
      web:
        ingressClassName: tailscale
        annotations:
          tailscale.com/proxy-class: default-proxy-class
        host: "setup02-airflow.tailac05db.ts.net"
        tls:
          enabled: true
          secretName: airflow-cert
        path: /
        pathType: Prefix
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule
    scheduler:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    webserver:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    triggerer:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
    workers:
      nodeSelector:
        node.kubernetes.io/location: cloud
      tolerations:
        - key: node.kubernetes.io/location
          operator: Equal
          value: cloud
          effect: NoSchedule
      persistence:
        storageClassName: "pd-standard"
    postgresql:
      primary:
        nodeSelector:
          node.kubernetes.io/location: cloud
        tolerations:
          - key: node.kubernetes.io/location
            operator: Equal
            value: cloud
            effect: NoSchedule
        persistence:
          storageClass: "pd-standard"
