minio:
    auth:
        rootPassword: ENC[AES256_GCM,data:PH77V4DiB0k=,iv:oFibsPvG6b9357DOx3m5QyvDidJqgiHfjpQAeLvYJME=,tag:9LTti7B/mBl1CVRtP8I1XA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTHZpWGpnQ0h5V1VWU1l2
            Mjk1Y1I5MVU4WDVsUHV4ajd3eWNTcXNYSGhrCmc5Zm9CNU13Y2xaK1NmVUFLa0xL
            Qkw3em4xVWZjajNyTFRmOUFCdDV2TFEKLS0tIEgyWTZ3S2I5STBhTGNoZGtuTTRZ
            TUFZekFjVE45L0UzRmxGZUZ1emhVcEkKSpLII0vaOUbHXDhVHzTJPqYF8rlz+CtQ
            qqxm+YtvI3A3UL+9F+cX8SX7UkgcnL89w8Sh1+oA34cSipAzrjBDJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:07:03Z"
    mac: ENC[AES256_GCM,data:yLXlxUrh2NRSF0aLL78/gQtDLN63OSYN6FOlRkoylcTVSWZvR4yq7bntNhMSsmutIvh/A9FS5S06AfPPHdUTH5zYrF5p79HID/IN97gFCa9y2niV5/DV5vCzczScdGYfE+ez3oey7uebkZEzmY7K3zYfu5obusL1gNjWJdSjyJI=,iv:mhiRQ6sLdErEs8idmfu9BamLl+/E5FIav/fUckRpGV4=,tag:WNthPapJuNBfUoVIVMH4NA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
