gitea:
    gitea:
        admin:
            password: ENC[AES256_GCM,data:nt1xv9BXJj8=,iv:Zir0q824VoB4kOuhAT06PWcleL4qxvAcG3L9JOmF0cc=,tag:DXxMfWiPbkvvo4nNt5gnkA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZEhkd2ZkdGdxTjh4c2Jr
            TyttTHZjUXFsTXJkc1pRTjVjUW0vNEU4c1ZZClZHTVZ2OVFzZkxObWlYbWI5OE5j
            bGYyVVFyU01hRTV0d0ptenEwU2V3M00KLS0tIG1HaHdQREdLdWo1T2Zjby9kMFRk
            VmdZS0ZFMERjVWdwUDlFSEhpT0dHZkkKG1shB1GnBdHK8wz27U/+XLElNBNL7z3i
            XXFreszE6tSGrEKK8TiNns8KSVUhREIy9sNPK/1FrzXJ9SflelY/DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:07:12Z"
    mac: ENC[AES256_GCM,data:GqSwfWqJ4DZxSiHJukvwzHNepoW/x2BDGuQIvtI3Ha9OKEEM9VhMxdDSW5EiUEzzT/zyHXP8zuDNLpSfgHv3K1crzKzRB/4HdUJ70BO7+FZZvHPjtd/Q5KzCImfvWOoRBpI0Vt3P2v6fdMtuQAz/sfE16MOL2h23n0AR0Jdir+c=,iv:L0Ymo1aWFVO3Ht7lzLx2gvB7W4I4G2XN/37Slb51WAg=,tag:uCuGsiptJyBLZbhd+PUQjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
