tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:Youo582MJjHssM0ja9Q0thA=,iv:yANQs5eNziqQWcbHqPUe0GIIix5wj9OG2nwBQ6/n+/Y=,tag:i4aSYdKtx59THjROl8Mn4Q==,type:str]
        clientSecret: ENC[AES256_GCM,data:0gEu2w66sWmibXG/KW95nijCBMpzz/n3yez1wxaIJv5Y6vvGzsfsFdRTzlc7iPDxAnN9hzyTk6Gjiytznh4hsQ==,iv:eYjUei6gKRgfIRS6e9XDCh9tgQC5xZRVJ8Y141kSpvA=,tag:tlA2C6iucI1md4O7KQ84rw==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcnd0OEgxTUtpSm1qR2dz
            RkEvQ2NrMm1ib2pLL3lPSXV0UTdOLzJYcjEwCkVoNTBoQlBEMWxRb0VrZGZNbjYx
            NE9NV0JVLzVncXRzRStYYXFJckFpcVEKLS0tIG9JMkFJaStFMHJscUFRWTNTUUZk
            eHJVZi9VakhRZzBmOWR2d0dQd0dzR3cKEwcU9zuFowr9/OBuZ9n8hzfN5mQhodsC
            brfVQO+PZ8HYCp0s/Dm4ObV+yisnNDrtN6fRBvJA/0Wi0+dOoC0d3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T22:25:52Z"
    mac: ENC[AES256_GCM,data:iHDdNEIpepBGIW5SlCi5xY43Ai+QdTIwmgQj4sH9jy5EA7FYEXUq9CgX5fQcb4+cZ7Ip1QmoODwjEXvRltpO/P446NDDGgQYubkPtaTw61W3RhuC6lN2sVEfk7cU5rON22Ycyjqm/fGH5aWgr0cvPEOSXWMLH2b/uQrM8hXgrio=,iv:gNpMbXgzVA9XWtiUK23N+ftEegG0zv71IUBA0KMuzIA=,tag:jEC8Ooo9BvO/L++3jsNIYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
