tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:m3BqWfEcypUeiKwZ5oCLY/I=,iv:4hAlRYlD7Lv/golIGoMUb8pNR1HU46qXMoJNVChdD/Q=,tag:vqLR14WyEMjQ4EXvJ4UNNg==,type:str]
        clientSecret: ENC[AES256_GCM,data:VsduZtJ5lb9lFD/Av0D2Gl4gzoOf80aTsUI+PZWKFm+xIv60SeD/rU8qTItZSjEAkOPYvAm8VIfcaXNGB+80TQ==,iv:8EhRBjiJHKsoEbNhP3eX4TLDKigLAJPjc4eZC9vlHd4=,tag:0TdlQl1bPuWDJpEML6hUgA==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFckxzRStmbGRxa0RiSGNN
            UGNJc1dHcHI0bWZvQ2R3UUpmTHB3RjkwcTFzCnlHNmxQTmxXdmZBQVIwc05XdThB
            QWVqZ1JhWFd4aGgyajVjTG51Q1RsZ1UKLS0tIDZLS1UvQTUvQ1poS0FPaHhPSnhO
            c1hqTFlWZXFMV0Jtemorc05PVnQzS1EKo2nRZxzHCnJ+Tl87I5mSHNGECTxj6Ns1
            13T2qSOKbxbNGIFT5BjBtYnG68gz8VjAhxRXLpESsRZnH1hrnEdCHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:07:27Z"
    mac: ENC[AES256_GCM,data:oOGaIrlRl8zaAtGOx9DITnAOrXEOMjFAfRUSwsfVTPlOGV119tBpC2EifMWTLtf01mEDJnSaqbPlQ/RVA/2OU1Q1l6ia197RtTcT5t2hDpwLoaJ34CBgWuPts4H+fkTvgBEGTkYqv3gfl3r4O2BpUpLWVYchwkmN2vZouLRo2+U=,iv:8ED3ZW0xzz1irsNEsArf1+Gql2Dm6bNV7iPZtk2P648=,tag:q/sfQIwut35rusXzB5VYMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
