tailscale-operator:
    oauth:
        clientId: ENC[AES256_GCM,data:wUpmC5zEcxB11QukVOw71sY=,iv:VPciAnb3EbwGGGIK94pTdVNz9JjTRCjRBZbGMYPkoSY=,tag:UZTWuvwaWL2V/9uFVmUinA==,type:str]
        clientSecret: ENC[AES256_GCM,data:VCrdQuFRS8vOTgvfbkiXOnLePZDsliKT/r3ENk0d5M4XzUmkPTZ6rtrrmVtQWuAWgQhcQM+aMY2NQyqEBPtgMQ==,iv:T2CAeaVydb8BQlJ8jECGd0jeq7Hm7F1vcEsu5G5EmX0=,tag:IBrtXYtJ0UsB+bz6U0FA4A==,type:str]
sops:
    age:
        - recipient: age144ehqvphpdmvkpntzu56wphw9rrezpu8j0j3kccq8lq2ufc9c96ss3fnkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0F5eWZqVGVWOUVwVDRh
            NDBIWkRqY1RGcXFpdFNlaS8vRUJkMXVVYVNnCjZLT1RhekVSaS9zR2VoMTJPOGQ4
            Tk1lRSs5K1AyVllVZG5PVFZrSzNoTDgKLS0tIHNDeENyTkV6ZkdYSkV3c29TVlFn
            ZmpSKzdPeTNiWXFSQTc3ZEkxUFBZWGsKWoBigjLeKSPHBIA/+P1HcE4Uvfu5+wOH
            0l508xxnM489eQWwbo0MIcVGsfvI2jotJLS2mtWgkQ3IXoLGcA+VTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T13:05:32Z"
    mac: ENC[AES256_GCM,data:umdYJcn+B4Rz9ABq1ED2oZRjOgCEwVVKKlDP4bVTxop9CmRXf/hlusH7oDHEhUwwh2eRqE71PqLMjCvnltK5y6Lzn3tEMsmqTSAk9jk/E2+42XjAmq7/+PIf+mjLqPZsFENdMfEOYKKXcoQWsHh1mvTsnuYPvMAPKAHe7JtEnXA=,iv:WYxT73Vu3rSU80nbmEiXwjmjLLCp/t5fg+/6jv6R4s0=,tag:JSKHiRYbqgiQPiHwtm606g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
