# top-level values consumed by the umbrella chart templates
proxyClass:
  name: default-proxy-class
  tolerations:
    - key: "node.kubernetes.io/location"
      operator: "Equal"
      value: cloud
      effect: "NoSchedule"

# sub-chart values
tailscale-operator:
  operatorConfig:
    defaultTags:
    - "tag:setup02-operator"
    hostname: "setup02-tailscale-operator"
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule
  proxyConfig:
    defaultTags: "tag:setup02-k8s"
    defaultProxyClass: "default-proxy-class"
