tailscale-operator:
  operatorConfig:
    defaultTags:
    - "tag:setup02-operator"
    hostname: "setup02-tailscale-operator"
    nodeSelector:
      node.kubernetes.io/location: cloud
    tolerations:
      - key: node.kubernetes.io/location
        operator: Equal
        value: cloud
        effect: NoSchedule
  proxyConfig:
    defaultTags: "tag:setup02-k8s"
