apiVersion: v2
appVersion: 19.0.0
dependencies:
- condition: mysql.enabled
  name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 9.12.3
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 18.1.9
- condition: kafka.enabled
  name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 30.1.6
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.3.0
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.11.0
- condition: airflow.enabled
  name: airflow
  repository: https://airflow.apache.org
  version: 1.9.0
description: A Helm chart for Open Source MANO (OSM)
icon: https://www.etsi.org/images/articles/logos/OSM.png
name: osm
type: application
version: 19.0.0
